package entregable.gui;

import entregable.logic.Persona;
import entregable.logic.Tools;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Display extends javax.swing.JFrame {

    private final Persona usuario;

    public Display(Persona _usuario) {
        this.usuario = _usuario;

        initComponents();

        // Load data name
        lbWelcome.setText("Bienvenido, " + this.usuario.getNombre().toUpperCase());

        this.desactivarModalInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOptions = new javax.swing.JList<>();
        btnOption = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbSaldoTitle = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        lbOperacion = new javax.swing.JLabel();
        fieldOperation = new javax.swing.JTextField();
        modalOperation = new javax.swing.JLabel();
        btnOperation = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbWelcome.setFont(new java.awt.Font("Nimbus Roman", 1, 24)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(173, 96, 82));
        lbWelcome.setText("Welcome, ");

        listOptions.setBorder(null);
        listOptions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Consulta", "2. Retiro", "3. Deposito", "4. Salir" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listOptions.setFocusable(false);
        jScrollPane1.setViewportView(listOptions);

        btnOption.setBackground(new java.awt.Color(212, 255, 0));
        btnOption.setText("Elegir operación");
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbSaldoTitle.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbSaldoTitle.setText("Saldo de la cuenta");

        lbSaldo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbSaldo.setText("Oculto");

        lbOperacion.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbOperacion.setText("Operacion");

        modalOperation.setText("Ingrese opcion valida");

        btnOperation.setBackground(new java.awt.Color(94, 228, 147));
        btnOperation.setText("Ejecutar operacion");
        btnOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperationActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Nimbus Roman", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(10, 9, 8));
        lbTitulo.setText("Cuenta Bancaria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(btnOption, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(113, 113, 113)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSaldoTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(lbSaldo)
                                .addGap(157, 157, 157))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTitulo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modalOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbTitulo)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSaldoTitle)
                            .addComponent(lbSaldo))
                        .addGap(108, 108, 108)
                        .addComponent(lbOperacion)
                        .addGap(32, 32, 32)
                        .addComponent(fieldOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(modalOperation)
                        .addGap(29, 29, 29)
                        .addComponent(btnOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
        this.mostrarOperaciones();
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperationActionPerformed
        // TODO add your handling code here:
        String nameOperation = lbOperacion.getText();
        this.ejecutarOperacion(nameOperation);
    }//GEN-LAST:event_btnOperationActionPerformed

    private void mostrarOperaciones() {
        boolean salir = false;
        do {
            String opcion = JOptionPane.showInputDialog(null, "1. Consulta\n2. Retiro\n3. Deposito\n4. Cerrar Sesión");

            switch (opcion) {
                case "1":
                    this.mostrarSaldo();
                    salir = true;
                    break;

                case "2":
                    this.mostrarSeccionOperacion("Retiro");
                    salir = true;
                    break;

                case "3":
                    this.mostrarSeccionOperacion("Deposito");
                    salir = true;
                    break;

                case "4":
                    System.out.println("Sesión cerrada");
                    this.terminarSesion();
                    salir = true;
                    break;

                default:
                    System.out.println("Ingrese opcion correcta");
            }
        } while (!salir);
    }

    private void mostrarSaldo() {
        double saldoInt = usuario.getSaldo();
        String saldo = String.valueOf(saldoInt);

        lbSaldo.setText("$ " + saldo);
    }

    private void mostrarSeccionOperacion(String _nameOperation) {
        lbOperacion.setText(_nameOperation.toUpperCase());
        lbOperacion.setVisible(true);
        fieldOperation.setVisible(true);
        modalOperation.setVisible(true);
        btnOperation.setVisible(true);
    }

    private void ejecutarOperacion(String tipo) {
        String ammountTxt = fieldOperation.getText();
        double ammount = Double.parseDouble(ammountTxt);
        fieldOperation.setText("");

        if (tipo.equals("RETIRO")) {
            if (this.usuario.retiro(ammount)) {
                mostrarResultadoOperacion("Retiro exitoso", new Color(0, 255, 0));
            } else {
                mostrarResultadoOperacion("El retiro falló", new Color(255, 0, 0));
            }
        } else {
            if (this.usuario.deposito(ammount)) {
                mostrarResultadoOperacion("Deposito exitoso", new Color(0, 255, 0));
            } else {
                mostrarResultadoOperacion("El Deposito falló", new Color(255, 0, 0));
            }
        }
    }

    private void mostrarResultadoOperacion(String mensaje, Color color) {
        modalOperation.setForeground(color);
        Tools.activarModal(modalOperation, mensaje);
        this.mostrarSaldo();
    }

    private void terminarSesion() {
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }

    private void desactivarModalInput() {
        // operation section hidden
        lbOperacion.setVisible(false);
        fieldOperation.setVisible(false);
        modalOperation.setVisible(false);
        modalOperation.setEnabled(false);
        btnOperation.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOperation;
    private javax.swing.JButton btnOption;
    private javax.swing.JTextField fieldOperation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbOperacion;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbSaldoTitle;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JList<String> listOptions;
    private javax.swing.JLabel modalOperation;
    // End of variables declaration//GEN-END:variables
}
